### ISSUE TITLE
Login handler logs credentials

### ISSUE THREAD

**Issue by mincrmatt12** [Arctos6135/scouting-web-app#5]
Right now when someone logs in, various lines in `login.ts` dump the entire request data (which has plaintext passwords in it)

(e.g. https://github.com/Arctos6135/scouting-web-app/blob/master/backend/login.ts#L25)

Can these logs be removed/sanitized?

**Comment by alexwaeseperlman** [comment]
Fixed with 9dab2d9d313e6029e5e8320f77ac781e06f136f8

**Comment by alexwaeseperlman** [comment]
Thanks for pointing this out, it was a very serious issue
